### ISSUE TITLE
OverflowError: cannot convert float infinity to integer

### ISSUE THREAD

**Issue by skwolvie** [pycaret/pycaret#102]
![image](https://user-images.githubusercontent.com/22741452/80956103-276f7380-8e1e-11ea-949f-3eec575ae0c4.png)

![image](https://user-images.githubusercontent.com/22741452/80956129-33f3cc00-8e1e-11ea-8f02-053c0578c484.png)

**Comment by pycaret** [comment]
Hi.

Can you please the dataset so I can try to reproduce error. 

Thanks

**Comment by DaGuT** [comment]
When you load the dataset, just add `.replace([np.inf, -np.inf], np.nan)`

E.g.
`pd.read_csv('./whatever.csv', sep=',').replace([np.inf, -np.inf], np.nan)`

This might solve the issue. Dunno, if I should do it at pycaret level. But if you want, I can make a pull request with fix.

**Comment by pycaret** [comment]
@DaGuT Where do you propose to make this fix? preprocess.py?

**Comment by DaGuT** [comment]
> @DaGuT Where do you propose to make this fix? preprocess.py?

No, I propose to make changes in setup function, that is classification.py, regression.py and clustering

https://github.com/pycaret/pycaret/pull/105

Honestly, I feel It's better to make a new function in utils.py to fix this issue in 1 place and then call it in all three places so that if you'd want to modify the fix, you would not have to do it multiple times. So you can reject my PR and ask me to do so and I will do so.

**Comment by pycaret** [comment]
@DaGuT I am holding-off on the PR for this one. I have contacted the author of preprocess.py and he is looking for a fix into preprocess.py since it serves all other module, it makes sense to fix it in one place. 

Thanks.
