### ISSUE TITLE
remove_multicollinearity parameter ignored

### ISSUE THREAD

**Issue by xandrade** [pycaret/pycaret#113]
Team, based on the documentation, the parameter `remove_multicollinearity` (for regression and classification) shouldn't drop the features with high correlation between the features and with the target. I tried with my own dataset and PyCaret's dataset, but these correlated features are always dropped. There are cases where you must keep all features (just a gentle warning should be enough). 

This is one example:

```
from pycaret.classification import *
from pycaret.datasets import get_data

dataset = get_data('blood', profile=True)
exp1 = setup(dataset, target='Class', remove_multicollinearity=False, )
```

Now, while dateset has these columns:Recency, Frequency, Monetary, Time, Class,
the X has Recency, Monetary and Time.

I do understand that Monetary is highly correlated with Frequency (ρ = 1), but if this parameter is equal to False, why they are dropped? Thanks for this great library and continuous support.

**Comment by pycaret** [comment]
@xandrade Thanks for your question. Very good one indeed.

Frequency and Monetary is 100% correlated that's why one of them is randomly removed. This is not a function of remove_multicollinearity.

100% correlated is forced remove because we had to avoid dummy variable trap when one-hot-encoding is performed. 

Unfortunately this is one of those scenarios where two numeric values "Frequency" and "Monetary" happens to be 100% correlated. 

If you do have any suggestions, please reach out.

I am closing this issue for now.

**Comment by xandrade** [comment]
Probably it wasn't the best example, but there are many. For example, imagine you have a two pressure sensors. You can calculate the diferencial pressure too and add this as a feature (example of process oil and gas). In this cases, there is a high correlation, not equal to 1 but close. However, the 3 features must be used and my any means excluded, otherwise the model will be biased.... 

Please, reconsider to have an option to don't drop correlated variables.
