### ISSUE TITLE
The results of catboost regressor are so different between cpu and gpu

### ISSUE THREAD

**Issue by xuzhang5788** [pycaret/pycaret#1130]
choosing "use_gpu=False or True" in setup, I got different results for catboost model. 

use_gpu=True
  | Model | MAE | MSE | RMSE | R2 | RMSLE | MAPE | TT (Sec)
-- | -- | -- | -- | -- | -- | -- | -- | --
Random Forest Regressor | 0.3228 | 0.2657 | 0.5154 | 0.6305 | 0.0404 | 0.0271 | 55.1210
Extreme Gradient Boosting | 0.3590 | 0.2913 | 0.5397 | 0.5948 | 0.0407 | 0.0298 | 4.2670
Light Gradient Boosting Machine | 0.3925 | 0.3458 | 0.5880 | 0.5191 | 0.0448 | 0.0327 | 1.1760
**CatBoost Regressor | 0.5311 | 0.5818 | 0.7626 | 0.1915 | 0.0588 | 0.0445 | 5.3970**

use_gpu=False 

  | Model | MAE | MSE | RMSE | R2 | RMSLE | MAPE | TT (Sec)
-- | -- | -- | -- | -- | -- | -- | -- | --
Random Forest Regressor | 0.3228 | 0.2657 | 0.5154 | 0.6305 | 0.0404 | 0.0271 | 54.5500
**CatBoost Regressor | 0.3560 | 0.2854 | 0.5342 | 0.6030 | 0.0404 | 0.0295 | 6.4560**
Extreme Gradient Boosting | 0.3597 | 0.2931 | 0.5414 | 0.5924 | 0.0409 | 0.0299 | 61.5780
Light Gradient Boosting Machine | 0.3925 | 0.3458 | 0.5880 | 0.5191 | 0.0448 | 0.0327 | 0.6610

Please help me to figure out how to setup gpu in a correct way. Many thanks

**Comment by Yard1** [comment]
This is an issue with Catboost, not PyCaret.

**Comment by moezali1** [comment]
@xuzhang5788 Can you please report the issue on Catboost repo? 

Link: https://github.com/catboost/catboost

**Comment by nateGeorge** [comment]
The hypeparameter search differs when using the GPU or not. Does anyone know why? It makes no sense to me.
You can see for grid search the depth is a smaller range of 1-8 instead of 1-11.

https://github.com/pycaret/pycaret/blob/c04bf2ccf34c6087e5b88f87623563acba0e95b9/pycaret/containers/models/classification.py#L1412

**Comment by nateGeorge** [comment]
I also noticed if you set `use_gpu=True` during `setup` and then try using catboost with `scikit-optimize` as the tuner, it doesn't work (the error is `ValueError: Dimension has to be a list or tuple.` and the problem is `tune_distributions["depth"] = (IntUniformDistribution(1, 8),)` where the last comma should be removed). I can open a pull request (or if someone else is faster they can), but I'm not sure if we should just remove the entire `if_gpu=True` block since as I said in my last post, it makes no sense to me to shrink the hyperparameter space when using GPU. My opinion is that the `if_gpu=True` block should be removed.

**Comment by nateGeorge** [comment]
@xuzhang5788 can you provide the hyperparameters the catboost models found? I'm wondering if the depth has maxed out.

**Comment by Yard1** [comment]
@nateGeorge Catboost documentation recommends lower depth values if Catboost is running on GPU.
