### ISSUE TITLE
Support for Arimax and Sarimax Models in timeseries branch

### ISSUE THREAD

**Issue by akashg116414** [pycaret/pycaret#1213]
please Support auto regressive model with seasonality like sarimax and arimax in compare_model, create_model and tune_model as Arima is not enough for data with seasonal behaviour.

**Comment by ngupta23** [comment]
Hi @akashg116414 , This is already present in the module (under development) to some extent. Note that `arima` is a general term in the `create_model`, Under the hood it is actually `SARIMA` so it takes seasonality into account.

The initial version will only support univariate analysis. When multivariate analysis (SARIMAX) is incorporated into the base `sktime` library, we will include that in `pycaret` as well.

**Comment by akashg116414** [comment]
Sarimax can be used for univariate Timeseries forecast as well, it need not multivariate always, AutoVIML and statsmodel.sarimax support Univariate timeseries as well. so can it be part of compare_model , create_model and tune_model.

How to choose between univariate and Multivariate in setup function.

**Comment by ngupta23** [comment]
Maybe I was not clear. We do support univariate analysis right now with SARIMAX in `pycaret` (`time_series` branch which is under development). We do not support Multivariate analysis right now since it is not there in the base `sktime` library. We will add multivariate analysis to `pycaret` once this capability is added to `sktime`.

To use SARIMAX for univariate analysis, see [this notebook](https://nbviewer.jupyter.org/github/pycaret/pycaret/blob/time_series/time_series_101.ipynb).

As you can see seasonality is accounted for in the model

![image](https://user-images.githubusercontent.com/33585645/116993508-30975880-ac9d-11eb-8d09-b9fa229e943a.png)

**Comment by ngupta23** [comment]
We recently also added support for `auto_arima` (univariate only for now) .
