### ISSUE TITLE
We need to get the dataset at each stage of datapreparation

### ISSUE THREAD

**Issue by sanath984** [pycaret/pycaret#1236]
We need to get the dataset at each stage of datapreparation  in mlflow 
for example after imputation 
after transformation
after PCA 
at each stage

**Comment by tvdboom** [comment]
Better late than never. This feature is not within the scope of mlflow since mlflow is tightly related to the model training and this is a feature about preprocessing. mlflow stores every model in a separate run. Storing datasets at different stages of preprocessing doesn't fit in their landscape.

I'm closing because of the date of creation. Feel free to reopen.
