### ISSUE TITLE
PyCaret Crashes Google Colab with Large Dataset and feature engineering[BUG]

### ISSUE THREAD

**Issue by schnetzlerjoe** [pycaret/pycaret#1259]
Hello! My PyCaret model constantly crashes on Google Colab with 501808 rows × 311 columns especially when I utilize the feature engineering tools and/or the feature selection option. What can I do to get this to stop crashing due to memory usage? I have tried GPU usage, etc.

My setup code is currently,

modSetup = setup(data = train, target = 'target', session_id=1234, use_gpu=True, feature_interaction = True, polynomial_features = True)

**Comment by Yard1** [comment]
Using feature interaction and polynomial features on such a big dataset will inevitably exhaust all memory due to multiple new columns being generated. While the process can certainly be optimized, the nature of it by itself needs very large amounts of memory. Therefore, with a dataset as big as yours it is not possible to do those feature preprocessing steps without massive amounts of memory and I would recommend turning them off. With so many features they shouldn't be necessary in the first place.
