### ISSUE TITLE
Removing selected algorithms from setup

### ISSUE THREAD

**Issue by souvikg10** [pycaret/pycaret#126]
Hi,
I have non-ASCII characters in my dataframe and i would like to avoid using lightGBM for it's known issues during compare_models() or feature_selection. 

Is there a way i can simply import selected algorithms i want to compare so i can omit lightGBM from the list. I could not figure out a way to do so

Thanks

**Comment by DaGuT** [comment]
compare_models(blacklist = ['lightgbm'])

**Comment by souvikg10** [comment]
cool thanks

**Comment by souvikg10** [comment]
@DaGuT ,
Sorry another question-what about during setup to calculate feature importance?
clf1 = setup(data = diabetes, target = 'Class variable', feature_selection = True)

can i blacklist a model during setup as well?

**Comment by DaGuT** [comment]
Sorry, I did not find anything that allows you to control feature selection methods (other than some of their parameters) in https://github.com/pycaret/pycaret/blob/master/classification.py setup function

Anyway, Let's ask @pycaret

**Comment by pycaret** [comment]
@DaGuT  Thanks for help as alwys.

@souvikg10 feature selection in setup when set to True, a subset of features are selected using a combination of various permutation importance techniques including Random Forest, Adaboost and Linear correlation with target variable. The size of the subset is dependent on the feature_selection_param. Generally, this is used to constrain the feature space in order to improve efficiency in modeling. When polynomial_features and feature_interaction are used, it is highly recommended to define the feature_selection_threshold param with a lower value.

Please see https://pycaret.org/feature-importance/ to learn more.

**Comment by souvikg10** [comment]
Hi,
Thanks for the explanation. Actually when i run the setup with a dataset with non-ASCII characters, lightGBM throws an error. I include the feature_selection param. My intention is to avoid using lightGBM. I can blacklist it during compare models but if i want to run feature importance, it also throws the same error during setup. How do i avoid using lightGBM during feature importance in my setup()? non-ascii handling is a known problem of lightGBM :(

**Comment by DaGuT** [comment]
Sadly, you cant. You will need to disable feature selection completely

**Comment by souvikg10** [comment]
Yeah, let's hope lightGBM address this issue soon. I am currently using compare_model and ignore lightGBM, and create individual models to get feature_importance

**Comment by ccll** [comment]
This shouldn't have closed, as it's a useful feature.
Can we reopen this issue and have `setup()` accept a blacklist parameter as `compare_models()`?
