### ISSUE TITLE
[BUG] model trained on fold_group column when using groupkfold cv 

### ISSUE THREAD

**Issue by Geethen** [pycaret/pycaret#1291]
I have been using the groupkfold cv strategy which requires me to specify a fold_groups parameter. The problem arises when this column remains as a feature in the model. if I specify the fold_groups column name within the ignore features argument. An error is returned. Any ideas to fix this? I know the fold_group column is being used as a feature to train the model because it appears in the feature importance plot.

pycaret version 2.3.1

**Comment by pycaret** [comment]
Hi @Geethen.

`fold_groups` parameter can also accept takes an array with shape (n_samples, ) where n_samples is the number of rows in the training dataset. You can pass an array with group values instead of passing the string with the name of the column in the dataset.

![image](https://user-images.githubusercontent.com/58118658/120944409-55e70e80-c702-11eb-8ddb-12f28f00aa80.png)

Hope this helps.

Thanks

**Comment by Geethen** [comment]
Hi,

Thanks for your response. I have tried specifying a numpy array with shape
(n_samples,). However, this raises the error AttributeError:
'numpy.ndarray' object has no attribute 'index'.

I am not sure if I am doing something wrong or if it is a bug. it seems
like it wants a list object?

thanks for your help,
Geethen
