### ISSUE TITLE
get the performance metrics for all hyperparameters from a grid 

### ISSUE THREAD

**Issue by pit9921** [pycaret/pycaret#1528]
Hi, i am not able to figure out hot to perform hyperparameter tuning with itertools:

```
clf = setup(data = train, target = 'h1n1_vaccine' )
rf = create_model('rf', fold=5)
best = automl(optimize = 'AUC')
print(best)
```

```
import itertools

hparams = {
          "max_features": np.random.randint(1, len(train.columns),20),
          "min_samples_leaf": [2,3,4,5,6],
          "criterion": ["gini", "entropy"]
}

X_train = get_config('X_train')
y_train = get_config('y_train')

for row in itertools.product( *hparams.values() ):
    kwargs = {k:v for k,v in zip(hparams.keys(), row)}
    model = RandomForestClassifier
    model.fit(X_train, y_train)
    score = model.score(X_test, y_test)
```

I got an error: TypeError: fit() missing 1 required positional argument: 'y'

Do you have somebody an experience with it?
**My goal is to get the performance metrics for all hyperparameters from a grid (see the hparams).** Is there any other way?

**Comment by Yard1** [comment]
The error is caused by you not instantiating the model, but this is a very complicated way of getting around to this. What you should do is use PyCaret's `tune_model` function like so:
```python
clf = setup(data = train, target = 'h1n1_vaccine' )
rf = create_model('rf', fold=5)
hparams = {
          "max_features": list(np.random.randint(1, len(train.columns),20)),
          "min_samples_leaf": [2,3,4,5,6],
          "criterion": ["gini", "entropy"]
}
tuned_rf, tuner = tune_model(rf, optimize = 'AUC', search_algorithm='grid', custom_grid=hparams, return_tuner=True)
```

This will return both the best model and the sklearn GridSearchCV object, which you can use to access metrics for each combination. It is also worth noting that PyCaret has built in search spaces for all models, and you may opt to use those instead of specifying your own grid.

Please refer to the [documentation](https://pycaret.readthedocs.io/en/latest/api/classification.html#pycaret.classification.tune_model) for details on what the parameters do

**Comment by moezali1** [comment]
@pit9921 Here is the sample code that I used to generate a grid that I think you are looking for:

```
from pycaret.datasets import get_data
data = get_data('juice')

from pycaret.classification import *
s = setup(data, target = 'Purchase', silent = True)

rf = create_model('rf')

tuned_rf, tuner = tune_model(rf, return_tuner=True)

pd.DataFrame(tuner.cv_results_)
```
![image](https://user-images.githubusercontent.com/54699234/131578927-1c9f17ca-8518-4352-b8ba-05709439f120.png)

Hope this helps.

**Comment by pit9921** [comment]
It works great! Thank you.
