### ISSUE TITLE
valueerror: the least populated class in y has only 1 member, which is too few. the minimum number of groups for any class cannot be less than 2.

### ISSUE THREAD

**Issue by skwolvie** [pycaret/pycaret#155]

**Comment by pycaret** [comment]
sa@skwolvie Can you please provide full traceback and also share the sample data you are using?

**Comment by rudreshmehta** [comment]
The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2

This is the error encountering.

Solution (from stackoverflow) : -
x_train, x_test, y_train, y_test = train_test_split(data_x,data_y,test_size=0.33, random_state=42)

By adding random_state might solve but in PYCARET it is abstract to user, So, cannot solve it.

**Comment by pycaret** [comment]
@rudreshmehta I believe you are doing classification? Can you share the value count of target variable and your code.

**Comment by swankyshahir** [comment]
hi, even i had the same problem, but on doing value counts of the target variable i found that one of the class value_counts was less than 2, so not possible to split the data into folds properly, so i removed that row which contained that instance and the problem was solved. Thanks Moezali and team for making this amazing stuff.

**Comment by swankyshahir** [comment]
and yes it was a classification problem

**Comment by pycaret** [comment]
@swankyshahir Thanks
