### ISSUE TITLE
Two level stacking models

### ISSUE THREAD

**Issue by Mohammedsaied89** [pycaret/pycaret#1680]
How could I implement two level with stacking models in pycaret

**Comment by moezali1** [comment]
@Mohammedsaied89 There was a function called `create_stacknet` in PyCaret 1.0 that used to do multi-level stacking. Since we have switched stacking implementation to scikit-learn's `StackingClassifier`, it is not possible to have multiple layers in stacking. There are only 2 layers:

(i) Base layer of models
(ii) Meta model (Logistic/Linear regression by default but can be changed).
