### ISSUE TITLE
`return_fig` to be added as a new parameter in plot_model of pycaret.time_series

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#1699]
`return_fig` to be added as a new parameter (default = False) in the `plot_model` function of `pycaret.time_series`.

**Comment by ngupta23** [comment]
Hi @moezali1 - Just thinking though this - why is `return_fig` needed? And if it is needed, should this be implemented in all modules (not just `time_series`)?

**Comment by ngupta23** [comment]
So, we will only have `save`, and `return_data`

1. If save = False --> then return figure (do not plot it as jupyter will plot it by default)
2. If save = True --> then display figure & return the file name

Example

1. `save=False, return_data=False` --> return fig   
2. `save=False, return_data=True` --> return fig, data
3. `save=True, return_data=False` --> return fig_name
4. `save=True, return_data=True` --> return fig_name, data

**Comment by ngupta23** [comment]
@moezali1 @Yard1 @satya-pattnaik 
The problem that I see now is that if we only return the fig when save=False without showing it, then we can not have 2 `plot_model` calls in 1 jupyter notebook cell. It will only display the last plot.

I think we should reintroduce the return_fig argument and it should work like this. Let me know your thoughts... 

| save  | return_fig | return_data | display_format | Action                   | Returns             | Notes                                                                   |
|-------|------------|-------------|----------------|--------------------------|---------------------|-------------------------------------------------------------------------|
| False | False      | False       | None           | fig.show()               | None                |                                                                         |
| False | False      | True        | None           | fig.show()               | data                |                                                                         |
| False | True       | False       | None           | None                     | fig                 | Do not do fig.show() since returned fig will be displayed automatically |
| False | True       | True        | None           | None                     | fig, data           | Do not do fig.show() since returned fig will be displayed automatically |
|       |            |             |                |                          |                     |                                                                         |
| False | False      | False       | streamlit      | st.write(fig)            | None                |                                                                         |
| False | False      | True        | streamlit      | st.write(fig)            | data                |                                                                         |
| False | True       | False       | streamlit      | st.write(fig)            | fig                 | Write to streamlit and return fig                                       |
| False | True       | True        | streamlit      | st.write(fig)            | fig, data           | Write to streamlit and return fig, data                                 |
|       |            |             |                |                          |                     |                                                                         |
| True  | False      | False       | NA             | fig.write_html(filename) | filename            |                                                                         |
| True  | False      | True        | NA             | fig.write_html(filename) | filename, data      |                                                                         |
| True  | True       | False       | NA             | fig.write_html(filename) | filename, fig       |                                                                         |
| True  | True       | True        | NA             | fig.write_html(filename) | filename, fig, data |                                                                         |

**Comment by ngupta23** [comment]
Until this is resolved, we are showing the figure by default internally and not returning the figure. Rationale is as follows

```python
# If we do not show but return instead, then the issue is that
# we can not have 2 plot_model calls in a single cell in jupyter
# since the first returned figure will be overwritten and not shown.
# Showing the figure and returning the object is also not an option
# as it will display the plot twice.
```
