### ISSUE TITLE
NameError: name 'display_id' is not defined when executing code in IDE

### ISSUE THREAD

**Issue by HenriqueAJNB** [pycaret/pycaret#175]
Hi there, 

I just got this error while coding execution in Visual Studio Code.

`NameError: name 'display_id' is not defined`

And here is code tried:

```
from sklearn.datasets import load_boston
import pandas as pd
from pycaret import regression

boston = load_boston()

df = pd.DataFrame(data=boston["data"], columns=boston["feature_names"])
df["MEDV"] = boston["target"]

exp_reg = regression.setup(
    data=df,
    target="MEDV",
    train_size=0.7,
    normalize=True,
    remove_outliers=True
)

model = regression.create_model(estimator='lr')
```

Is there somehow to check if user is executing code either in prompt, IDE or Jupyter Notebook/Google Colab? 

How can I contribute to solve this problem?

For this specific case, I just comment 5 lines and it worked. 

```
1689 # if verbose:
1690 #     display_ = display(master_display, display_id=True)
1691 #     display_id = display_.display_id
...
2015 # if verbose:
2016 #     update_display(master_display, display_id = display_id)
```

Thanks!

**Comment by pycaret** [comment]
@HenriqueAJNB Hi.. this is a known issue in first release. Version 1.0.0 is not optimized to work in environment that doesn't support HTML such as IDE or Python command line. This issue has been fixed in classification.py and regression.py in dev-1.0.1 branch. Feel free to test. 

Please close this issue once you tested it on dev-1.0.1 branch.

Thanks.
