### ISSUE TITLE
Needs to get control date_features in preprocessing 

### ISSUE THREAD

**Issue by GDGauravDutta** [pycaret/pycaret#1877]
Presently, date_features are encoded using One Hot Encoding but as a user, I feel it can be handled better with Ordinal Encoding or Cardinal Encoding.

Presently, we cannot control this in setup. 

Thanks
GD

**Comment by tvdboom** [comment]
This behavior will change in the new release. Useful information will be extracted from the datetime column (day, month, year) and those (numerical) columns are added to the dataset instead of the original. If you think of better/faster/simpler ways to handle datetime columns, please feel free to drop your ideas here.
