### ISSUE TITLE
GPU support for XGBoost, CatBoost (and other models)

### ISSUE THREAD

**Issue by xenonsb** [pycaret/pycaret#201]
Hi there, thanks for creating this library! Having a low-code library to run ML experiments is definitely a nice fresh idea :)

Having said that, are there any plans to allow for using GPU for models that support GPU acceleration (like XGBoost through gpu_hist, CatBoost through GPU)? This could significantly decrease training time required when we're running on GPU-enabled machines.

Thanks in advance!

**Comment by pycaret** [comment]
@xenonsb Thanks

In next release we will support **kwargs in functions so that you can access all parameters of estimator. So for example you will able to pass gpu_ram_part parameter in catboost in next release. 

For now - I am tagging this as an enhancement and upon next release I will close this log.

Thanks
