### ISSUE TITLE
Unable to plot after loading model

### ISSUE THREAD

**Issue by Ley002** [pycaret/pycaret#2023]
I have created a regression model. With the following code:

```
from pycaret.datasets import get_data
dataset = get_data('insurance')

from pycaret.regression import *
exp_reg101 = setup(data = data, target = 'charges', session_id=123,
                  bin_numeric_features = ['age', 'bmi'],
                   remove_multicollinearity = True,
                  profile = True)

best = compare_models(sort = 'R2')
tuned_best = tune_model(best)
final_model = finalize_model(tuned_best)
save_model(final_model,'regresion_model_insurance')
```

I load the model, but I am unable to create any of the plots, There is no error.

```
model = load_model('regresion_model_insurance')
plot_model(model._final_estimator, plot = 'error')
```
![Captura](https://user-images.githubusercontent.com/19893256/148281265-01f9b11f-88a7-4070-90fc-1113881b5084.PNG)

**Comment by moezali1** [comment]
@Ley002 There is a function called `save_config` and `load_config`. Since `plot_model` uses many environment variables you must save the environment using `save_config` (it will save many global vars as a pickle object) and then use `load_config` to load that in the Notebook before you use `plot_model`. Hope this will help.

**Comment by john6214058** [comment]
%matplotlib inline
you can run above before plot ,then will auto show the image
