### ISSUE TITLE
[BUG][time_series] Installation Issue

### ISSUE THREAD

**Issue by VinayChaudhari1996** [pycaret/pycaret#2114]
Hello Team,

###  Issue: 
Unable to use pycaret ts  on google colab 

Instalation status = **Success** 

`!pip install -U pycaret-ts-alpha
`

![image](https://user-images.githubusercontent.com/42869040/152107087-72cd9a06-86a9-4853-a277-6e4a9250b3a6.png)

```python
ImportError: cannot import name 'safe_indexing' from 'sklearn.utils' (/usr/local/lib/python3.7/dist-packages/sklearn/utils/__init__.py)
```

How to fix this issue?

Thanks

**Comment by ngupta23** [comment]
`sktime` made a new release (0.10.0) which is breaking something. I just made a new release for `pycaret-ts-alpha` pinning `sktime` to a prior version (0.9.x). Can you try again and let me know if you still face any issues?

**Comment by fkiraly** [comment]
I think this is not `sktime` related.

Quick look indicates that `sklearn` made `safe_indexing` private in version 0.22.0, since then it's `_safe_indexing`.
https://scikit-learn.org/stable/modules/generated/sklearn.utils._safe_indexing.html

https://stackoverflow.com/questions/65602076/yellowbrick-importerror-cannot-import-name-safe-indexing-from-sklearn-utils

So, you've been calling a long deprecated function, which, probably by some combination of mildly pushed lower bounds in `sktime` surfaced the problem.

**Comment by fkiraly** [comment]
here, this is the root issue, seems to be `yellowbrick`
https://github.com/DistrictDataLabs/yellowbrick/issues/1137

**Comment by VinayChaudhari1996** [comment]
Just 2 weeks before , it was working fine on Google colab.

**Comment by ngupta23** [comment]
@VinayChaudhari1996 The temporary fix that I released should allow you to install it now. This will use version sktime 0.9.0. We will try to release a permanent fix later which will allow the use of sktime 0.10.0 and all other relevant libraries properly.

**Comment by VinayChaudhari1996** [comment]
Great @ngupta23  !!!
