### ISSUE TITLE
Please Manage links in a better way

### ISSUE THREAD

**Issue by bibhabasumohapatra** [pycaret/pycaret#2148]
**Describe the bug**

Every time I want to learn something or search some feature about PyCaret (not taking away the fact that PyCaret is great)

![image](https://user-images.githubusercontent.com/68384968/153723288-bc64ae6f-7221-4fd2-ad6e-0109d0b4884d.png)

Please link all the these link to helpful docs

**Comment by ngupta23** [comment]
What link is this? Also, did you try clicking on "moved here"? What happens when you do that?

**Comment by moezali1** [comment]
@bibhabasumohapatra We have moved the documentation [here](https://pycaret.gitbook.io). As long as that link is taking you on the documentation, there is nothing wrong with this. 

The reason I had to be a redirect like that is because there are tons of articles and tutorials that were referencing directly to a specific page on pycaret.org for example pycaret.org/classification.

Hopefully you will find this [new documentation](https://pycaret.gitbook.io) useful.

**Comment by bibhabasumohapatra** [comment]
> @bibhabasumohapatra We have moved the documentation [here](https://pycaret.gitbook.io). As long as that link is taking you on the documentation, there is nothing wrong with this. 
> 

![IMG_20220213_083234.jpg](https://user-images.githubusercontent.com/68384968/153736456-d3acd10e-f69e-4bc1-85a0-0384387190e4.jpg)

The problem is not it redirects to pycaret.gitbook.io
The problem is redirects everything to pycaret.gitbook.io

Searching _numerical features pycaret_   should take me to numerical features_  on pycaret.gitbook.io

Rather it takes me to _numerical features pycaret_ on old website which redirects to home page. 

For ex:
If you search random forest sklearn it would take you to Random forest page of sklearn not the home page of sklearn.

**Comment by ngupta23** [comment]
@bibhabasumohapatra For now can you use the search capability on the new documentation page itself?

![image](https://user-images.githubusercontent.com/33585645/153861513-248e6b01-05a3-4907-95cf-047d0652bf6d.png)
