### ISSUE TITLE
setup() got an unexpected keyword argument 'experiment_custom_tags' [BUG]

### ISSUE THREAD

**Issue by fabSchAdastra** [pycaret/pycaret#2172]
**Describe the bug**

According to the documentation there should be a parameter called 'experiment_custom_tags', but I receive the error message.

**To Reproduce**

from pycaret.datasets import get_data
juice = get_data('juice')
from pycaret.classification import *
exp_name = setup(data = juice,  target = 'Purchase', experiment_custom_tags = {"test": "test"})

**Expected behavior**

The purpose is to have custom tags logged in MLflow

**Versions**
<details>

import pycaret
pycaret==2.3.5

</details>

**Comment by ngupta23** [comment]
This feature has not been released yet. You can try to install from `master` branch if you want to try this out.

**Comment by fabSchAdastra** [comment]
@ngupta23 is there a timeline to when expect this feature?

**Comment by moezali1** [comment]
@ngupta23 The API reference doc is automatically built using docstring and there is no bifurcation between development and production branch in sphinx hence the API reference is always built of the master branch and hence the gap between API doc and released functionality. 

@Yard1 Any idea how to solve this in long run? I guess we should have a `master` branch that is synced to the released version and then all the PR's should be submitted on the `develop` branch. Any other ideas?

On the other hand [official docs](https://pycaret.gitbook.io/docs/) are manual and that's why you will not see this parameter there as it will be only be done after release.

**Comment by ngupta23** [comment]
Yes having a separate develop branch is a good idea.

**Comment by moezali1** [comment]
@fabSchAdastra The feature has now been released in `2.3.9`.
