### ISSUE TITLE
[BUG]: FugueBackend with spark backend

### ISSUE THREAD

**Issue by reza1615** [pycaret/pycaret#2322]
Pycaret version 2.3.8 on the Databricks the below code shows **unexpected keyword argument 'available_plots'** error and crash. Dask backend is ok

``` python
from pycaret.datasets import get_data
from pycaret.classification import *

setup(data=get_data("juice"), target = 'Purchase', n_jobs=1, silent=True)

test_models = models().index.tolist()

from pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()

compare_models(include=test_models, n_select=2, parallel=FugueBackend(spark))
```
![image](https://user-images.githubusercontent.com/2202483/159704975-1d578b67-4492-462b-9f4c-17a5578b0dea.png)

**Comment by goodwanghan** [comment]
I am investigating

**Comment by goodwanghan** [comment]
It seems I can't reproduce this issue on Databricks. I am using Spark 3.2.1.

On my environment, there is no such issue.

In order to reproduce your error, I have to do something like

```python
compare_models(include=test_models, n_select=2, parallel=FugueBackend(spark), avaialbe_plots=[])
```
 But obviousely this parameter isn't on your function call.

Also searching the entire repo of pycaret, the keyword `avaialbe_plots` is only in the unit tests.

So here are my suggestions:

1. Restart a new clean notebook
2. Make sure you don't run any pycaret tests before running this code
3. Make sure there is no keyword `available_plots` between your `setup` and `compare_models` call

I don't think you have to do all the above things to make it work, it is just to help you figure out where the problem is.

Please let me know if this works @reza1615

**Comment by goodwanghan** [comment]
I have tested on the exact same environment as yours, and I still can't reproduce this issue. Everything works fine.

<img width="863" alt="image" src="https://user-images.githubusercontent.com/21092479/160792623-b42de25a-1e19-41d7-a77c-77dd9fdf4917.png">

@reza1615 do you mind testing on 10.4 LTS (spark 3.2.1)?

**Comment by reza1615** [comment]
@goodwanghan: i tested with 10.4 LTS and have the same issue

**Comment by kvnkho** [comment]
I can't replicate it too on the same setup. PyCaret 2.3.9 for me. Running on Databricks. Just confirming you are running on Databricks and not connecting remotely?

![Screen Shot 2022-04-01 at 12 45 41 AM](https://user-images.githubusercontent.com/32503212/161196589-907717ba-31af-4fc0-88f5-7c2cf67fd522.png)

**Comment by reza1615** [comment]
I am directly running on databricks with the pycaret 2.3.9

**Comment by reza1615** [comment]
I checked it on another cluster which is a shared cluster and shows the below error 
![image](https://user-images.githubusercontent.com/2202483/161299808-e0745f1a-be28-4a37-b415-c9407ba1a269.png)

**Comment by goodwanghan** [comment]
@reza1615 maybe it is helpful to setup a meeting so I can understand the difference between our environments.

Before that, can you try to install

```
pip install git+https://github.com/goodwanghan/pycaret.git@fugue-fix#egg=pycaret[full]

```

instead of 

```
pip install pycaret[full]==2.3.9
```

Because this can install the latest code change that could prevent this issue on your side.

But meanwhile it will be great if we can meet and we need to understand the root cause of this.

Thank you so much for your help!
Han

**Comment by reza1615** [comment]
pip install git+https://github.com/goodwanghan/pycaret.git@fugue-fix#egg=pycaret[full]
It doesn't work on notebook it has issue with #

**Comment by reza1615** [comment]
I installed based on your repo and the error still the same

**Comment by goodwanghan** [comment]
This is how I installed it

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/21092479/161333234-1ae8266f-a5d3-4f38-a181-d23e18b18f25.png">

**Comment by reza1615** [comment]
I don't have edit access

**Comment by goodwanghan** [comment]
hmmm i see, both I and @kvnkho both install the pycaret as a cluster library.

Is it possible your spark cluster pycaret is of a different version?

Maybe we should setup a meeting to investigate.
