### ISSUE TITLE
Include StatsForecast models

### ISSUE THREAD

**Issue by FedericoGarza** [pycaret/pycaret#2414]
**Is your feature request related to a problem? Please describe.**
I would like to include some [`StatsForecast`](https://github.com/Nixtla/statsforecast) models in the PyCaret time series module; in particular a faster `AutoARIMA`. 

What would be the best way to do it?

**Comment by ngupta23** [comment]
Hi @FedericoGarza  Yes this is planned, but we need to have an architecture discussion for that and what the user interface will look like. Please see details in this issue: https://github.com/pycaret/pycaret/issues/2323.

I will close this and we can continue the discussion on the other issue if needed. statsforecast AutoARIMA will be the pipe cleaner for this.

**Comment by ngupta23** [comment]
Hi @FedericoGarza As a short-term enhancement, I would recommend that we get the various `croston` variants added to `sktime`. `sktime`, only has the basic version right now so adding the TSB version, etc. would be an added advantage. We should be able to include that right away in pycaret once that is added to `sktime` since there is no additional library in pycaret that provides those models. 

Thanks!

**Comment by FedericoGarza** [comment]
Sure, @ngupta23! I'll be working on that :)

**Comment by ngupta23** [comment]
Awesome. Thanks @FedericoGarza
