### ISSUE TITLE
Transformed train and test data has less number of features

### ISSUE THREAD

**Issue by ganapatihl** [pycaret/pycaret#261]
Hi,

orginal data has 466 features. after train and test split it become 256 features, how its happened, could you help me on this.

![image](https://user-images.githubusercontent.com/29286110/86367599-c89d6d80-bc99-11ea-9484-c06e2a9946d5.png)

**Comment by ganapatihl** [comment]
this will happen only when we pass numerical feature list.

**Comment by pycaret** [comment]
@ganapatihl Thanks for reporting. I guess this is happening because by default PyCaret removes variable with perfect collinearity i.e. two variables are 100% correlated. Unfortunately there is no way to disable that in 1.0x. However in next release there is a parameter **remove_perfect_collinearity** being added to _setup()_. 

Can you please install pycaret-nightly and test it on the same dataset after turning remove_perfect_collinearity to False.

Please let me know how it goes.

**Comment by pycaret** [comment]
Labelled as **enhancement**

**Comment by ganapatihl** [comment]
Hi Team,

How to know which all features are correlating and correlating with which
features. Because before adding features to pycaret i have removed highly
correlated features. please let me know how to get those feature lists in
pycaret version 1.0.0

*Thanks and Regards:*


*Ganapati H L*

*Linked IN :https://www.linkedin.com/in/ganapati-h-l-26885660/
<https://www.linkedin.com/in/ganapati-h-l-26885660/>*
