### ISSUE TITLE
[ENH]: Option to set the mark color in compare_models()

### ISSUE THREAD

**Issue by epsilon-deltta** [pycaret/pycaret#2702]
### Describe the feature you want to add to this project

TIC

### Describe your proposed solution

![image](https://user-images.githubusercontent.com/45354219/177070437-c58a402b-67bd-41bb-9092-77711d7f891c.png)
In dark mode, i cant see well markable scores cuz of that yellow mark. Could u make the option to choose the mark color.
Or is there any solution?

**Comment by DanieleBaranzini** [comment]
same issue as @epsilon-deltta   : )  and color change option for the highlighted ones?

**Comment by mbellitti** [comment]
I checked the source, and it looks like the background colors "yellow" and "lightgreen" are hardcoded [here](https://github.com/pycaret/pycaret/blob/1a2c21244e484476d5a35d3308c83e1d92d68fd3/pycaret/utils/generic.py#L52) and [here](https://github.com/pycaret/pycaret/blob/1a2c21244e484476d5a35d3308c83e1d92d68fd3/pycaret/internal/pycaret_experiment/supervised_experiment.py#L305). They are set using the Styler interface of pandas (see [here](https://pandas.pydata.org/pandas-docs/stable/user_guide/style.html)).

As a temporary workaround, you can override the colors after the table has been computed, for example doing

```python
board = get_leaderboard()
board.loc[:,["Model Name","AUC"]].style.highlight_max(props="background-color:#004d40").highlight_min(props="background-color:#862d4b")
```

which gives a much more readable result

![image](https://user-images.githubusercontent.com/5868852/222478250-ea9a06af-917c-4ac1-be2c-083e75967246.png)

**Comment by ngupta23** [comment]
Thanks @mbellitti  for digging deeper into it. This would make a good first PR if you are interested in incorporating it in the package itself.

**Comment by mbellitti** [comment]
I'll look into it. Are there specific style guidelines I should adhere to?

**Comment by ngupta23** [comment]
Awesome. Thanks!

**Comment by mbellitti** [comment]
It turns out that the highlighting is done in two different ways: 
- using the `setup_highlight` function in `utils/generic.py`
- using `highlight_max` in `supervised experiment`. 

The pull request I just made addresses the first one only. They are two separate problems, so I will work on the second in a separate pull request.

Zooming out a bit, I would like to unify these behaviors and expose the whole `Styler` interface of all reports, but that is a much larger change, should I try working on it?
