### ISSUE TITLE
Question - Overwrite String as Data Type on Setup

### ISSUE THREAD

**Issue by bjuncklaus** [pycaret/pycaret#271]
Hi, is it possible to overwrite the data type on setup to Strings? I don't want my data to be categorical I want it to be String/Object, however I can't find a way do it.

![image](https://user-images.githubusercontent.com/9988985/86944726-84d5b880-c11e-11ea-8119-04457ec8bf61.png)

**Comment by pycaret** [comment]
@bjuncklaus Can you please clarify a little. Why do you want data types to be of type string? All strings/object are converted into categorical so that encodings can be done. 

Please provide more details about use-case of why you would want certain columns to be string? This will help us to answer your question.

**Comment by bjuncklaus** [comment]
Hi, I want to do some feature engineering with the Strings, for example use the Name to extract the Title (Mr, Miss, Mrs).

**Comment by pycaret** [comment]
@bjuncklaus Yes. please do it before passing your data into setup.

Thanks.

**Comment by bjuncklaus** [comment]
Thank you
