### ISSUE TITLE
[BUG]: plot_model, evaluate_model not producing any output in  databricks

### ISSUE THREAD

**Issue by Prashavu** [pycaret/pycaret#2831]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

No graph/plot is produced after riunning the code

### Reproducible Example

```python
fig = plt.figure(figsize=(18,6))
ax = fig.add_subplot(5,2,1)
plot_model(blender, plot='cooks', save=True, verbose=False, scale=1.1)
ax = fig.add_subplot(5,2,2)
plot_model(blender, plot='manifold', save=True, verbose=False, scale=1.1)
#plt.savefig('plots_cooks_and_manifold.png', dpi=300, pad_inches=0.25)
plt.show()
```

### Expected Behavior

matplotlib plot expected

### Actual Results

```python-traceback
nothing is displayed after running the code to plot
```

### Installed Versions

<details>
2.3.10
</details>

**Comment by asmaier** [comment]
The [pycaret NLP tutorial](https://nbviewer.org/github/pycaret/pycaret/blob/master/tutorials/Natural%20Language%20Processing%20Tutorial%20Level%20Intermediate%20-%20NLP102.ipynb) also doesn't show any plots on databricks. Mainly the problem is, that it internally pycaret uses [plotly/cufflinks](https://github.com/pycaret/pycaret/blob/master/pycaret/nlp/__init__.py#L1978) to create the plots, which does not work out of the box with databricks zeppelin notebooks. Unfortunately the pycaret `plot_model()` function also does not return the figure object so that it is impossible to use the databricks renderer for plotly in combination with pycaret like 

```
import pandas as pd
import cufflinks as cf
cf.go_offline()

df = pd.DataFrame([1,2,3,3,2,1])

fig = df.iplot(asFigure=True)
# using the databricks renderer to show the figure
fig.show("databricks")
```

See https://github.com/nicolaskruchten/plotly_img_test/blob/master/Untitled.ipynb

**Comment by moezali1** [comment]
@asmaier I have tested the latest rc4 release of pycaret `pycaret==3.0.0rc4` on Databricks community edition. `plot_model` function works fine. `evaluate_model` doesn't work because of no support of IPython. 

In Databricks Runtime 11.0 and above, Python notebooks use the IPython kernel to execute Python code. 

Read More: https://docs.databricks.com/notebooks/ipython-kernel.html
