### ISSUE TITLE
[BUG]: Turn off Dataframe preprocessing while setting `preprocess`= True

### ISSUE THREAD

**Issue by Prashavu** [pycaret/pycaret#2929]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

`preprocess= True` is mandatory to do `fix_imbalance`=True .
But this bascially engineers new columns that I wan to turn off. 
For example two columns X and Y having calues 0 and 1 ; 
2 Columns like X_0 and X_1 are created , which I want to turn off.

HowCan i still have my imbalance fixed while preventig this behaviour

### Reproducible Example

```python
from imblearn.over_sampling import *
adasyn1 = ADASYN(sampling_strategy='all')
from pycaret.datasets import get_data
juice = get_data('juice')
from pycaret.classification import *
exp_name = setup(data = juice,target = 'Purchase',fix_imbalance=True,fix_imbalance_method=adasyn1,preprocess=True)
```

### Expected Behavior

Should not change exisiting columns of orginal dataframe

### Actual Results

```python-traceback
NA
```

### Installed Versions

<details>
2.3.10
</details>

**Comment by noah8287** [comment]
fix_imbalance _is_ a form of preprocessing in the sense that it's an adjustment made to the data prior to fitting a machine learning model. Since `preprocessing=False` is meant to disable all preprocessing steps pycaret has built-in, I'm not sure what you're asking for makes sense. 

That said, it would be nice to have an option to disable all preprocessing steps _except_ for the one(s) the user specifically requests.

OP, for your case, it sounds like pycaret may be interpreting some of the columns in your data as being categorical and sending them to OneHotEncoder. Assuming your data is all numeric, you should be able to prevent this unwanted behavior by setting `categorical_features=[]`.

**Comment by Prashavu** [comment]
@noah8287 Even before sending to `setup` I have defined what is numerical) and what is categorical(my categorical in the data set im working on consists of only 0/1). but I do not want one hot encoding for my categorical. How can I prevent any other preprocessing except smote(fix_ibalance)

**Comment by tvdboom** [comment]
Use the latest rc version of pycaret: `pip install --pre pycaret`. This version will **not** one-hot encode columns with only 2 classes. Also, make sure pycaret treats your columns as numerical since they only contain 0/1. Use `categorical_features=[]` as @noah8287 suggests or change the type of the column before setup
