### ISSUE TITLE
[ENH]:  Linear regression formula in R language from Pycaret

### ISSUE THREAD

**Issue by AndIaAnd** [pycaret/pycaret#2976]
### Describe the feature you want to add to this project

Hello, if you know in R language linear regression have some formula from parameter in model 
https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/lm
http://imagedrop.xyz/viewImage.php?name=uploads/img_2022-09-19-14-02-18_6328766a7bd95.png
http://imagedrop.xyz/viewImage.php?name=uploads/img_2022-09-19-14-02-35_6328767b6885c.png
http://imagedrop.xyz/viewImage.php?name=uploads/img_2022-09-19-14-02-54_6328768e88e10.png
you can see this in formula predictor transformation
maybe you can add "predictor formula transformation" in pycaret? 
I really love your library, the lack of this feature is the only thing that makes me run to R again and again and use it, please. I think it's not difficult to write formulas for variable columns, I think it's even very easy!
book from
James_G._Vvedenie_v_statisticheskoe_obuchenie_.Fragment.pdf

### Describe your proposed solution

1) input data-set
2) add formula about column (use numpy or pandas) 
`import pandas as pd`
`import numpy as np`
`dates = pd.date_range('1/1/2000', periods=8)`
`df = pd.DataFrame(np.random.randn(8, 4), index=dates, columns=['A', 'B', 'C', 'D'])`
`s = df['A']`
`print("s",s)`
`s1 = df['A'] ** 2 # this is a formula`
`# i think good enough it's a console or area to input formula `
`print("s1",s1)`
3) create func who take create a function to easily apply formulas to columns

**Comment by ngupta23** [comment]
Since pycaret just relies on sklearn models under the hood, you should open this issue with sklearn. 
Alternately (a little more involved), if you want the statistical outputs, you can wrap the linear regression model from `statsmodels` into a sklearn compatible model and add that as a custom model in pycaret. This will return the statsmodels linear regression model to you which you can probe further to get the statistical outputs.
