### ISSUE TITLE
[INSTALL]: Upgrade to 2.3.10 and still requires scikit-learn==0.23.2

### ISSUE THREAD

**Issue by jmsuthar** [pycaret/pycaret#3012]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

macOS-12.6-x86_64-i386-64bit

### Installation Method

pip install

### pycaret Version

2.3.10

### Python Version

3.8

### Description

As per [requirements.txt](https://github.com/pycaret/pycaret/blob/master/requirements.txt#L10), it should point to greater version of scikit-learn. However while trying to install, it still refers to 2 years old version 0.23.2.

Reference snapshot
![image](https://user-images.githubusercontent.com/16442349/193595189-90816613-b0fa-4ffc-88ca-8735952b6cb4.png)

**Comment by ninjit** [comment]
I believe this is intentional (actually required) per the installation guide (which you marked as read):
 
![Screen Shot 2022-10-03 at 10 00 24](https://user-images.githubusercontent.com/753263/193635892-fe1ba08a-287d-42fc-b9b8-1510ab2deaf4.png)

The requirements file on github master is for the current development version (3.x) of pycaret which I gather will relax some of the == package requirements.

```pip install pycaret``` will currently install the latest 2.x version
if you want to try the 3.x branch, use
``` pip install --pre pycaret```
instead

**Comment by jmsuthar** [comment]
Okay that make all sense. Thanks a lot 👍
