### ISSUE TITLE
Question: Providing train and test sets to Pycaret 2

### ISSUE THREAD

**Issue by sparvaneh** [pycaret/pycaret#313]
Congratulation on releasing Pycaret 2!
I have training and test sets that are created outside of Pycaret. Can I use Pycaret 2 with those datasets?

**Comment by pycaret** [comment]
@sparvaneh One hack around would be to use set_config parameter to change X_train, X_test, y_train and y_test after setup function is completed but in this case you cannot use inference pipeline of PyCaret for production because you have overwritten all the preprocessing by using set_config. Example:

**# load X_train, X_test, y_train, y_test**
X_train = pd.read_csv('X_train.csv)
X_test = pd.read_csv('X_test.csv)
.
.


**# load dataset**
data = pd.read_csv('data.csv')

**# init setup**
from pycaret.classification import *
clf1 = setup(data, target = 'target-name-here')

**# set config**
X_train = set_config('X_train', X_train)
X_test = set_config('X_train', X_test)
.
.

Hope this helps.

**Comment by pycaret** [comment]
@sparvaneh Even though I have already provided the hack around this but the functionality will become available in the next release `2.2` (expected by end of Sep). You will be able to pass separate `train` and `test` set in the `setup` function.

**Comment by pycaret** [comment]
@sparvaneh 

This issue has been fixed in the `pycaret-nightly` release. Please install pycaret-nightly using `pip install pycaret-nightly`. Feel free to open a new issue, in case the problem persists. This fix will be published to PyPi as `pycaret==2.2.0` on October 28, 2020.
