### ISSUE TITLE
Logs.log

### ISSUE THREAD

**Issue by eonsmile** [pycaret/pycaret#315]
Anyway to disable auto outputting of logs.log via some flags?

**Comment by pycaret** [comment]
@eonsmile Nope. Is there is a reason you want to disable? Maybe we can mark this as enhancement and somebody can work on making this functionality optional, if that make sense.

**Comment by eonsmile** [comment]
It's not something I need in my workflow, so I don't want some extra unnecessary files in my working directory.

**Comment by pycaret** [comment]
@eonsmile At the moment it;s not possible to disable system logs. However if you want you can delete the file using os module.

**Comment by joschkazj** [comment]
Hi,

first of all many thanks for putting together this package! Ever since reading the [book by Kuhn and Johnson](http://appliedpredictivemodeling.com/) and working with caret in R I've been wanting an equivalent Python library.

>@eonsmile Nope. Is there is a reason you want to disable? Maybe we can mark this as enhancement and somebody can work on making this functionality optional, if that make sense.

For me the use case is an application wrapping a PyCaret model. I've packaged the application using PyInstaller and it is distributed with a setup wizard as a "conventional" Windows application. After installation it's placed in the system's program folder (`C:\Program Files (x86)`) *where normal users don't have write permissions* -- but PyCaret wants to create its log file there. As PyCaret is imported in different modules, monkey-patching would require editing some external libraries as well, so re-configuration of the logger appears to be impractical.

Therefore I suggest to make the logging handler configurable, why do you hard-code a file output?

**Comment by pyaf** [comment]
@pycaret I'm manually creating a separate log file for my project. I'd like to know if there's a way to disable the auto logs.log file creation functionality of pycaret.
