### ISSUE TITLE
[BUG]: X_train and X_train_transformed

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#3195]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

What is the purpose of `X_train` and `X_train_transformed`. If the goal is to keep `X_train` in original state without any transformations then It's not working that way. For example if I ignore a column by using `ignore_features` in the setup. get_config('X_train') returns a dataframe that doesn't show the ignored column. In this example `X_train` and `X_train_transformed` is exactly same. Is this intentional? If yes - what's the rationale?

![image](https://user-images.githubusercontent.com/54699234/209213094-12f06286-b553-4a4f-8f3f-93f490527b75.png)

### Reproducible Example

```python
..
```

### Expected Behavior

read above

### Actual Results

```python-traceback
read above
```

### Installed Versions

rc5

**Comment by tvdboom** [comment]
This is intended. Ignored columns are always dropped because its not part of the pipeline. You could argue that `X_train` is not showing the "real" original data but changing that would require too much trouble because of how the rest of the data properties are implemented. That's also the reason the shape was wrong in #3194, although that was easy to fix. It's the only thing that changes the shape though. The rest is original.

X_train and X_train_transformed are not the same. Look at the column `Store7`

**Comment by moezali1** [comment]
Gotcha @tvdboom
