### ISSUE TITLE
please add start_date and end_date feature for time_series predict_model()

### ISSUE THREAD

**Issue by sathishkumar999** [pycaret/pycaret#3219]
### Describe the feature you want to add to this project

Hi pycaret team @ngupta23 , @moezali1  and @Yard1 

In time_series predict_model, I have seen that we have input parameter as 'fh' where we can predict for number of days if it's trained on days. I'm requesting to add start_date and end_date parametrs to predict for range of date. by default these paramerts should me none and optional. and if user wants to forcast for the range of dates, he can mention by using satrt_date and end_date. even it should supoort along with time

##
tickets_forecast_daily = predict_model(estimator = loaded_model, start_date = [optional], end_date=[optional])
print(tickets_forecast_daily)

plot_model(tickets_forecast_daily)

### Describe alternatives you've considered, if relevant

...

### Additional context

...

**Comment by ngupta23** [comment]
> In time_series predict_model, I have seen that we have input parameter as 'fh' where we can predict for number of days if it's trained on days. I'm requesting to add start_date and end_date parametrs to predict for range of date. by default these paramerts should me none and optional. and if user wants to forcast for the range of dates, he can mention by using satrt_date and end_date. even it should supoort along with time

This feature is not available in the underlying sktime library. If you want pycaret to support this, you will have to put in a request in the sktime repo first. Once that is implemented in sktime, we can add it here as well. 

But to be frank, it seems this will needs a lot of changes and may not be as robust because of differences in how the start and end dates will interact with the frequency of the data. For example, if the data is weekly with weeks starting on Monday, but user enters start and end day on a Tuesday, there will be lot of internal checks that will be needed. Same extends to all frequency types. So the alternate of having to specify fh seems like a fair compromise.

I will close this for now. You can reopen if it gets implemented in sktime.
