### ISSUE TITLE
[BUG]: MAE & RMSE have the exact same values when using custom fold_strategy in pycaret.time_series

### ISSUE THREAD

**Issue by NasreddineD** [pycaret/pycaret#3220]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description
Hi, you should be able to reproduce the output with the following code. It doesn't look right to me.
```
from pycaret.time_series import *
from sktime.forecasting.model_selection import ExpandingWindowSplitter
from pycaret.datasets import get_data
data = get_data('airline')

my_custom_cv = ExpandingWindowSplitter(fh=12,initial_window=50 ,step_length=12)
s = setup(data, fold_strategy=my_custom_cv)

s.compare_models()
```
![image](https://user-images.githubusercontent.com/87130252/210186498-eb951723-2f06-41f7-a002-8fa4203c11eb.png)

### Reproducible Example

```python
from pycaret.time_series import *
from sktime.forecasting.model_selection import ExpandingWindowSplitter
from pycaret.datasets import get_data
data = get_data('airline')

my_custom_cv = ExpandingWindowSplitter(fh=12,initial_window=50 ,step_length=12)
s = setup(data, fold_strategy=my_custom_cv)

s.compare_models()
```

### Expected Behavior

MAE & RMSE should show different results.
I have tried it with different datasets.

### Actual Results

```python-traceback
MAE & RMSE are the same
```

### Installed Versions

<details>
pycaret '3.0.0'
</details>

**Comment by ngupta23** [comment]
That is because fh = 12 has a slightly different meaning in sktime vs. pycaret. In sktime fh = 12 means that you are only interested in the 12th future point and no other point before that. In pycaret fh = 12 is a short hand for the first 12 future points. 

If you want to use a custom splitter and are interested in the first 12 points, use np.arange(1, 13) instead of 12. 

Also, it seems that you are using a very old version pf the time series module which has been deprecated. It would be better to upgrade to the latest version (use a fresh environment for this)

```
pip install --pre pycaret
```
```
