### ISSUE TITLE
[DOC]: data_func does not appear to be more efficient

### ISSUE THREAD

**Issue by danielhstahl** [pycaret/pycaret#3575]
### pycaret version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)

### Location of the documentation

https://pycaret.gitbook.io/docs/get-started/preprocessing/other-setup-parameters

### Documentation problem

The documentation implies that using the `data_func` parameter may be more efficient than using the `data` parameter when doing parallel/distributed training.

However, the code here: https://github.com/pycaret/pycaret/blob/6d959150f5c63c30f255838cbc458069acdda99a/pycaret/classification/oop.py#L752C12-L753 just calls `data_func` as part of setup; which should have no difference in performance than simply passing in the dataframe into the setup function.

### Suggested fix for documentation

Either actually make the code more efficient for distributed/parallel training or drop the implication that this could be more efficient.

My use case is having a small notebook environment connected to Dask running on large EC2s.  It would be great to have the notebook "coordinate" the distributed training without having to load the data in the notebook itself.

**Comment by ngupta23** [comment]
@goodwanghan - Could you help with this? Seems to be related to Fugue.

**Comment by goodwanghan** [comment]
@danielhstahl thanks for asking, this is a good question, let me explain why this is necessary.

This `setup` function will run on both driver side and worker side to setup the environment if you use Spark, Dask or Ray. It will firstly run on the driver side, the input parameters will be recorded [here](https://github.com/pycaret/pycaret/blob/6d959150f5c63c30f255838cbc458069acdda99a/pycaret/classification/oop.py#L740-L749), which is before materializing the data. The recorded parameters will be used to also run on the worker side to setup individual environments.

So, if you pass in a `data_func`, workers will call the function to get the data. But if you pass in the real data, because it's recorded in the parameters, the drive will have to broadcast the data to each worker. That can be an expensive operation.
