### ISSUE TITLE
[BUG]: all tests are failing

### ISSUE THREAD

**Issue by celestinoxp** [pycaret/pycaret#3789]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

All tests are failing. Before they didn't fail and now they fail. I suppose the reason is an incompatibility with third party packages that probably these packages have been updated to new versions.
I propose that new versions of third party packages be supported, such as sktime which is now at version 0.24, but pycaret is very behind and only supports up to sktime < 0.22

I think that package support for newer versions could solve some problems, as well as prediction results could be better and faster.

### Reproducible Example

```python
.
```

### Expected Behavior

.

### Actual Results

```python-traceback
.
```

### Installed Versions

<details>
github tests
</details>

**Comment by ngupta23** [comment]
Seems to be caused since this PR was merged. 

https://github.com/pycaret/pycaret/pull/3773/files

@tvdboom @Yard1 - FYI ...

**Comment by ngupta23** [comment]
The reason is that time series `_create_model_with_cv` signature does not have `error_score` in it. This PR adds `error_score` in the call which causes the issue since all arguments passed are positional. Let's try to change it to explicit non-positional args in the future when we are making changes in the future if possible (for clarity and ease of debugging).
