### ISSUE TITLE
ValueError: need at most 63 handles, got a sequence of length 65

### ISSUE THREAD

**Issue by nasospat** [pycaret/pycaret#38]
When i try to run tune_model() on Windows server I receive the following error 

`Exception in thread QueueManagerThread:
Traceback (most recent call last):
  File "d:\anaconda3\envs\pycaret\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "d:\anaconda3\envs\pycaret\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "d:\anaconda3\envs\pycaret\lib\site-packages\joblib\externals\loky\process_executor.py", line 615, in _queue_management_worker
    ready = wait(readers + worker_sentinels)
  File "d:\anaconda3\envs\pycaret\lib\multiprocessing\connection.py", line 859, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "d:\anaconda3\envs\pycaret\lib\multiprocessing\connection.py", line 791, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 
`

I tried to run it on two different Windows servers using different Anaconda enviroments with Python 3.6.10 and 3.7.7 and had the same error.

**Comment by nasospat** [comment]
It seems that this is a known issue of loky library. 
https://github.com/scikit-learn/scikit-learn/issues/13354
As it says loky is broken on windows with more than 60 cores. A solution could be to provide the user the ability to set the maximum cores for the processes.

**Comment by mahmoudyusof** [comment]
does manually setting the `n_jobs` parameter of the `setup` function solve the problem? since it is -1 by default which uses all available threads. so maybe limiting it solves the problem

**Comment by pycaret** [comment]
@nasospat Did you tried changing `n_jobs` parameter in `setup` to `None`

**Comment by koh-joshua** [comment]
This is a common problem with loky when there's > 60 logical processors (i.e. 30 physical cores).

For example, on my threadripper 3970X (32 physical cores, 64 logical processors), using n_jobs=-1 will cause this error. The same error happens for sklearn and joblib because they use loky backend for parallel multicore processing. 

In my case, I set n_jobs=30 (30 physical cores, 60 logical processors) to avoid the error:

pycaret_exp = setup(data=data, target=target, n_jobs=30)  # example pseudocode

To conclude, if you have >30 physical CPU cores, please set n_jobs=30 max. 

How do we proceed beyond 30 physical cores? One workaround is use a library like Dask for multicore processing or joblib using Dask as the backend - the PyCaret team may consider this?
