### ISSUE TITLE
[INSTALL]: 

### ISSUE THREAD

**Issue by KingKai69** [pycaret/pycaret#3826]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

Linux-5.15.120+-x86_64-with-glibc2.35

### Installation Method

pip install

### pycaret Version

3.2.0

### Python Version

3.10.12

### Description

Hey community, i want to run the time series tutorial (https://colab.research.google.com/github/pycaret/pycaret/blob/master/tutorials/Tutorial%20-%20Time%20Series%20Forecasting.ipynb) that does not work.

Line --> from pycaret.time_series import * <-- throws the error "ImportError: cannot import name 'LegacyVersion' from 'packaging.version' (/usr/local/lib/python3.10/dist-packages/packaging/version.py)"

I am using Google Colab and tried to install pycared using
1. pip install pycaret[full]
2. pip install pycaret-ts-alpha

Both options do not work. Any help is appreciated

### Installation Logs

<details>

Replace this line with the installation logs.

</details>

**Comment by celestinoxp** [comment]
@KingKai69  This is not a pycaret problem. What happens is that after installing pycaret you have to restart google colab for the installation to be completed.

Follow these steps:
- create a cell at the top of the notebook with the command: !pip install pycaret[full]
-then in the runtime menu click on restart and run all

Okay, it worked for me! If you continue to have problems, you can provide more details, otherwise you can close this issue. Thanks
