### ISSUE TITLE
Is it possible to provide test dataset directly, bypassing test/train split?

### ISSUE THREAD

**Issue by brinew27** [pycaret/pycaret#436]
I am working with a time series classification dataset which contains multiple discrete "windows" of data. I intend to train on windows 1-4 for example and test against windows 5-6, which will hypothetically help with generalization to any future window. The % test/train split doesn't work well with this as if I do a fixed percent (ie 70%), I will likely get windows 1-4, with a bit of window 5, in the train set, and the test set will only contain partial window 5 and all of window 6. This will make it easier for the model to get higher scores on the test set, as data is leaking from window 5 into training, where ideally it would be entirely unseen.

This would be easily fixed if I could provide the train and test sets myself, (manually split 1-4 to train, and 5-6 to test), but as far as I can tell from looking at the pycaret code, it always passes through a test/train % split in the setup step.

Am I missing an option/workaround for this or would passing discrete train/test data be a new feature?

Thanks!

**Comment by Yard1** [comment]
Doesn't seem like it'd be that hard to add, I can take a look at it tomorrow.

**Comment by pycaret** [comment]
@brinew27 This is because `regression` and `classification` modules were never intended for times series. There is a separate module being worked out at the moment which will allow for a split that is applicable for time series data. 

However, you can always overwrite X_train, X_test, y_train, y_test after `setup` is executed using the `set_config` function. See https://www.pycaret.org/set-config for more details.

Hope this helps.

**Comment by brinew27** [comment]
Wonderful, that should definitely work to manually overwrite after setup. Yeah, I recognize that doing classification on time series data is not a usual use case (it's actually tick level stock data, so not strictly time-series), but I think this should work well for me for now, thanks!
