### ISSUE TITLE
Could we have a new test that checks pycaret.classification where setup has imbalance=True?

### ISSUE THREAD

**Issue by yashmehta10** [pycaret/pycaret#467]

**Comment by pycaret** [comment]
@daikikatsuragawa FYA.

I think what we need to do now is incorporate all the different preprocessing combinations that can be incorporated in `setup`. Coverage will increase a lot by doing that. However, we have to decide on how should we do it, whether all preprocessing options in one `setup` call or multiple combinations with different preprocessing features. There are over 15+ preprocessing params that we can use.

Let me know your thoughts.

**Comment by pycaret** [comment]
@yashmehta10 : @daikikatsuragawa is already working on enhancing our unit tests and has already made a lot of progress in a short time. Please feel free to reach out to @daikikatsuragawa and see if you can extend any help and work together (if @daikikatsuragawa needs help in there).

**Comment by pycaret** [comment]
I will take care of this.

**Comment by rotimi2020** [comment]
I think for now inbalanced dataset is not working using pycaret because if you use evaluate() and under class report u found our that the recall is very low.
The best you can do it,use your traditional code(R or python),duplicate your class by using smote and export it out using to_CSV() and feed it back to pycaret.
Tnks
