### ISSUE TITLE
Get Label Encoded

### ISSUE THREAD

**Issue by SSITB** [pycaret/pycaret#535]
How can i get the Label Encoded from the setup of the model?
I know i can print them and save in dictionary, is there a function that print 'Label Encoded'

**Comment by pycaret** [comment]
@SSITB Thanks. There is no separate function but you get the mapping in the information grid you get after you run the `setup` function. You can create your own dictionary from that point.

If you are asking this question in reference to `predict_model` then please note in 2.1 we have changed the behavior. Now `predict_model` will return `Label` as the original input instead of encoding. So for example, if your dataset has values "default" "no-default", `predict_model` will return the same `default` or `no-default` in the `Label` column instead of encoded 1 or 0. This is to make it more human-readable. 

Hope this answers the question.

**Comment by SSITB** [comment]
Perfect, looking forward to 2.1 👍

**Comment by lbaiao** [comment]
Do I have to copy/paste the label encoding from the information grid? Is there a more efficient to access the encoding?
