### ISSUE TITLE
Got an issue when I run the regression model in pycaret 2.0

### ISSUE THREAD

**Issue by whiran** [pycaret/pycaret#553]
When I run regression model , whole note book got stuck at the time of **TheilSen Regressor** runing. Kindly help someone in this regard. 
![2020-08-27 11_42_39-](https://user-images.githubusercontent.com/7403939/91420183-ea6a3980-e871-11ea-9cac-abd8d2698ecd.jpg)

**Comment by pycaret** [comment]
@whiran `TheilSen Regressor` doesn't scale well. I would suggest you can `blacklist` this just like `ransac`.

The algorithm calculates least-square solutions on subsets with size n_subsamples of the samples in X. Any value of n_subsamples between the number of features and samples leads to an estimator with a compromise between robustness and efficiency. Since the number of least square solutions is “n_samples choose n_subsamples”, it can be extremely large and can, therefore, be limited with max_subpopulation. If this limit is reached, the subsets are chosen randomly. In a final step, the spatial median (or L1 median) is calculated of all least square solutions.

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.TheilSenRegressor.html

Hope this helps.
