### ISSUE TITLE
Pycaret 2.0 and Streamlit deployment issue in Heroku

### ISSUE THREAD

**Issue by ashishgopal1414** [pycaret/pycaret#567]
Hi Team,
First of all, fabulous work!

I was trying to create an app with "streamlit" and "pycaret" and deploy it in heroku.

If I use "pycaret 1.0" the app is deployed successfully, but with "pycaret version 2.0", the size of dependency files becomes huge and crosses the heroku threshold of 500 MB slug size

Any help would be appreciated.

**Comment by Yard1** [comment]
Can you try to deploy Docker using the provided Dockerfile instead?

**Comment by ashishgopal1414** [comment]
> Can you try to deploy Docker using the provided Dockerfile instead?

I am unaware of the process to deploy using Docker. Can you please help me with the process if there are any tutorials for the same or link etc. ?

**Comment by Yard1** [comment]
https://devcenter.heroku.com/categories/deploying-with-docker

**Comment by pycaret** [comment]
@ashishgopal1414 Sorry to hear you are having issues. I think soon `Heroku` is reducing the `slug size` further to 300mb from 500mb so even if you try to add `.slugignore` for now to barely make it at 500mb, it won't work in future once it is reduced to 300mb.

I have written many articles for deploying models using Docker containers on Azure, AWS, and GCP. Almost all of them provide a joining credit of $300 - $500 and it should be good enough for learning. You can find all the articles here: https://github.com/pycaret/pycaret/tree/master/resources

**Comment by salilathalye** [comment]
Is there a way to create a streamlined module for interferencing/prediction that will have a smaller footprint than pycaret? When we load a pickle file containing the pipeline and model, do we really need all the rest of the codebase that is needed to create and tune a model and build the pipeline?

Also is there a page where we can see the size of the pycaret "footprint" by version number. It surprised me recently that a simple catboost model + pipeline created in PyCaret 2.2.3 and used by streamlit 0.73.1 created a slug of size 574MB! This could be one of the downsides of using an "all-in-one" module such as PyCaret because it imposes a larger RAM requirement to serve models in a Production setting.
