### ISSUE TITLE
Updated requirements.txt: install dependencies via conda

### ISSUE THREAD

**Issue by joschkazj** [pycaret/pycaret#581]
Hi,
this project appears to be very interesting, I'm looking forward to applying it to my modeling problems!

When installing the package using conda I stumbled upon some mis-named packages in `requirements.txt` which I've updated to **enable direct installation of most dependencies via conda** (I prefer to let conda handle my packages).
As I haven't tried this package, yet, I didn't invest the time to prepare a PR but wanted to share the updated
 list: [conda_requirements.txt](https://github.com/pycaret/pycaret/files/5156697/conda_requirements.txt)

Installation then becomes:
```shell
conda config --append channels conda-forge
conda create -n pycaret-sandbox --file conda_requirements.txt
pip install pycaret
python -m ipykernel install --user --name pycaret-sandbox
```

Hope this helps
Joschka

**Comment by pycaret** [comment]
@joschkazj Thanks. There are few people already working on it. The last thing I have heard about this issue is that there is `xgboost` on `conda`. I am not very familiar with conda so can't be of any help here but I am linking you to the original issue and closing this was. https://github.com/pycaret/pycaret/issues/21
