### ISSUE TITLE
X has 11 features per sample; expecting 12

### ISSUE THREAD

**Issue by SSITB** [pycaret/pycaret#693]
Hi

I trained a classification model however when testing it am getting unexpected  error.
X has 11 features per sample; expecting 12

I am sure that the number of feature used in prediction are same for the training.

When I added more data for the training dataset, I got another error
ValueError: query data dimension must match training data dimension

**Comment by SSITB** [comment]
When i save the model without finalize the issue is resolved, the end model should be saved with or without?

**Comment by pycaret** [comment]
@SSITB Can you please upload your notebook and sample dataset so that we can investigate what is causing the issue.

As in terms of `finalize_model`, it depends on the use-case. If the split sample was fair, finalizing shouldn't have any impact on model performance. In fact in the next release we are changing the behavior of `automl` function which by default finalize the model. We are changing the default value to `False`.
