### ISSUE TITLE
Default Transformation = false not working 

### ISSUE THREAD

**Issue by VinayChaudhari1996** [pycaret/pycaret#765]
Pycaret - 2.0.0
____

Dataset used :- Diamond 
Problem :- Regression

**How do I use original data without any additional transformed features after setup** ?

1) `Transformation = False` not working 

Original shape of data : (4200,8)
Even I false the transformation , 

Transformed train set :- (2939,29)
Transformed test set :- (1261,29)

I don't want that extra 29 columns , what should I do ? 

![IMG_20201027_193510~2](https://user-images.githubusercontent.com/42869040/97312848-f2535380-188b-11eb-800f-e1f52b280c4d.jpg)

2) Let's say , 
I have missing values and I change param `Missing value = True` .

In the end how can I access my cleaned dataframe object ? 

Currently `setup()` method return tuple.

Did anyone have solution ?

Thanks ,

**Comment by pycaret** [comment]
@VinayChaudhari1996 Transformation Train Set and Transformed Test Set shows the shape of the dataset after transformations. The increase in the number of columns is likely due to One Hot Encoding. If there are categorical values in your dataset, they are automatically encoded, otherwise, subsequent functions for training will not work.

Are there any categorical features in your dataset? Can you show the head of the original data here?

**Comment by VinayChaudhari1996** [comment]
1) Transformation issue fixed 

2) For cleaned data frame object after preprocessing `get_config()` method is worked for me 

Thanks,
