### ISSUE TITLE
Results worse with SMOTE

### ISSUE THREAD

**Issue by roberthoyt** [pycaret/pycaret#777]
I am analyzing the COVID-19 data that [[Kaggle]used for a data competition. https://www.kaggle.com/dataset/e626783d4672f182e7870b1bbe75fae66bdfb232289da0a61f08c2ceb01cab01?select=dataset.xlsx

I excluded anyone with missing data, so I ended up with a cohort of 658 patients, with 10% of them testing positive for COVID. I was anxious to try out the SMOTE option to fix the imbalanced dataset but was surprised to see the performance actually worsened after I changed fix imbalance to TRUE so that SMOTE would be used. I selected XGBoost for my initial model because it had the best performance

**Before**  
AUC = .85 Recall = .55 Precision = .65
**After**
AUC = .80 Recall = .51 Precision = .52

I don't think anything is wrong with PyCaret but I was seeking an expert opinion as to why balancing the classes would actually worsen the performance. Thanks

**Comment by pycaret** [comment]
@roberthoyt 

We cannot comment on these results. However, in pycaret==2.2 you can also pass the `sample_weight` parameter for estimators that allows it. For example below is the documentation of Logistic Regression:

![image](https://user-images.githubusercontent.com/58118658/97505327-1fb50580-194f-11eb-88ad-63a4468903e7.png)

Maybe you can try passing weights instead of SMOTE to see if things get better?

**Comment by sathishkumar999** [comment]
@roberthoyt 
hey could you post classification report.

**Comment by roberthoyt** [comment]
[COVID PyCaret (1).pdf](https://github.com/pycaret/pycaret/files/5458624/COVID.PyCaret.1.pdf)

**Comment by roberthoyt** [comment]
> @roberthoyt
> hey could you post classification report.

Please see my posted Jupyter Notebook
