### ISSUE TITLE
Documentation : add a second level in the left table of content

### ISSUE THREAD

**Issue by danbricedatascience** [pycaret/pycaret#796]
In [documentation](https://pycaret.readthedocs.io/en/latest/index.html) add a second level to the left table of content to enable quick browsing of each function.

**Comment by pycaret** [comment]
@danbricedatascience The documentation is created automatically using sphinx. I don't know If we can control the sub-section in this situation? Would you know how to do it?

**Comment by danbricedatascience** [comment]
I don't know for sphinx but generaly use Mkdocs and it have such option is the [styling option](https://www.mkdocs.org/user-guide/styling-your-docs/)

```
navigation_depth: The maximum depth of the navigation tree in the sidebar. Default: 4.
```

With google I found it, maybe it can help : https://www.sphinx-doc.org/en/1.5/templating.html?highlight=depth

**Comment by Yard1** [comment]
It's not possible currently, due to how API doc autogeneration works. We'd need to manually add a header to each function. Perhaps this could be done in the future.

**Comment by rajpratyush** [comment]
Hi @pycaret I would like to contribute on this issue. Do let me know if I can work on this. your guidance will be highly appreciated. Many thanks,

**Comment by pycaret** [comment]
@rajpratyush Sure. What are your thoughts in terms of the request @danbricedatascience has raised? 

Basically, we need a second level of navigation under the main module sections. For example: under `classification` it should have `setup`, `compare_models`, `create_model` .... as sub-sections. 

Hope this makes sense. Please let me know if you have any questions.

![image](https://user-images.githubusercontent.com/58118658/105568110-ed743380-5d04-11eb-8d50-f96414ffa8d3.png)

**Comment by rajpratyush** [comment]
@pycaret I understand it Lemme have a day or do to understand how to use sphinx so that i can work on it

**Comment by rajpratyush** [comment]
well the point @danbricedatascience has made is actually very important adding a second level would help the user browse through the docs more easily, like one who wants to lookup only for a specific function. but instead of adding a second layer we can't we create a dropdown sub menu in under each main module just like you mentioned. @pycaret I think that would be more feasible.

**Comment by pycaret** [comment]
@rajpratyush Take a stab at it. I am okay with whichever method, the goal is to make it easier to navigate.

**Comment by rajpratyush** [comment]
@pycaret sure lemme have a look at it

**Comment by rajpratyush** [comment]
@pycaret I have looked at it and yes we can add a second level of menu to it can you just guide me where exactly the css and the rst files are there in the repositroy so that i can chnage them to accomodate the required changes and also please tell me what kinds of links we should put up in second level of submenu

**Comment by Yard1** [comment]
They are in the `docs/source` folder.

**Comment by ngupta23** [comment]
@rajpratyush Are you still working on updating the docs?

**Comment by rajpratyush** [comment]
Sorry i had left this for a long time due to exams i will start working on it from today though if anyone wnats to take up pls take it
