### ISSUE TITLE
Big errors with predict_models for classification

### ISSUE THREAD

**Issue by javierperezcastan** [pycaret/pycaret#805]
Hi, 
Thank you very much for your work. It is amazing. 
I have a database that I would like to apply classification techniques. I have follow the different steps you use in your tutorial. I have trained a rf , I have tuned it to optimize 'f1' and once I apply the predict_model I can obtain the database with the label and score of the predict_model(). 
The problem arises when I compare the return metrics [accuracy, precission ...] with the confusion matrix. 
I have also compared the real value of the confusion matrix with the values obtained with the predicion_model and they are correct. However, they are completely deviated from the metrics returned by the predict_model().

The script is located at https://github.com/javierperezcastan/github-slideshow/blob/master/Exp_1_flujos-questions.ipynb

**Comment by Yard1** [comment]
Where possible, metrics use the probability scores instead of a binary correct/incorrect score. That is most likely what's happening here.

**Comment by javierperezcastan** [comment]
Using the confussion matrix and obtainnig the predicted value of the predict_model() they do not correspond with the formulaes of accuracy =TN / (TN+FP) and recall = TN / (TN+FN). If you are using the probability scores, how do you calculate the respective values of these metrics?
Thx

**Comment by Yard1** [comment]
Sorry, I was mistaken. What I said only applies to AUC. This is due to how we handle multiclass problems. However, this behavior should not be triggered for binary problems.

I just pushed commit 499ac03df22d7b5a73ed2b42fbcd8edba12207a5 that should fix this issue. Could you run
`pip install --upgrade --user git+git://github.com/pycaret/pycaret.git` to install PyCaret's development version and try again?

**Comment by javierperezcastan** [comment]
It actually works, thank you very much for your attention¡
