### ISSUE TITLE
[2.3] Preprocessing Refactoring

### ISSUE THREAD

**Issue by Yard1** [pycaret/pycaret#834]
All PyCaret transformers need to be refactored to conform to sklearn API (separate X and y). In this iteration, support only for Pandas is required To this end:
* Individual transformers need to be refactored - opportunities to improve performance should be considered
* A new pipeline class inheriting from `imblearn` Pipeline needs to be created to allow for additional features (ensuring that the X and y are pandas objects etc.)
* A new "pipeline" meta estimator class for y needs to be created to facilitate target transformation (details to follow)
* New tests should be added for individual transformators

The end result should have all PyCaret transformators being usable as a part of a sklearn workflow, provided that they receive Pandas objects.

This is necessary for passing Pipelines to CV and scalability.

**Comment by wkuopt** [comment]
Hi, I am interested in working on this. Thanks!

**Comment by Yard1** [comment]
Please make any PRs to `preprocessing-refactoring` branch.

**Comment by wkuopt** [comment]
Hey @Yard1, I was going through the surrogate imputer and found that this could probably be done with the boolean parameter add_indicator (https://scikit-learn.org/stable/modules/impute.html#marking-imputed-values), which exists for both the simple imputer and the iterative imputer. 

Do you see any potential issues removing the surrogate imputer? I feel that it will be easier to ensure the consistency of the imputed results since we won't need to worry about maintaining both the suggorage imputer and the other 2 imputers, e.g., making sure that the data types that they consider are the same.

Also, do we have plans to do add different imputation strategy for the time columns, e.g., rolling average. Right now it's only imputed by the most frequent values, which can probably be implemented as a special case of the categorical columns.

**Comment by Yard1** [comment]
I believe the surrogate imputer was left unfinished by the original author of preprocessing module. It was not available for users. I think it can be safely removed.

We have not had any plans for extra imputation strategies, but it would be good if you could structure the code in a way to facilitate easily adding new ones if it changes in the future.
