### ISSUE TITLE
Pycaret crashing both in Kaggle and Google Colab on small datasets

### ISSUE THREAD

**Issue by minhaajre** [pycaret/pycaret#966]
Less than 1500 row dataset utilizes all the RAM and session crashes everytime i use either Kaggle or Google Colab. Here is the link to notebook

https://colab.research.google.com/drive/1BPfpFh47FuWTE2gXaN63gsJpM-6I0HgH?usp=sharing

**Comment by pycaret** [comment]
@minhaajre Thanks for reporting. Can you please make the Notebook public and also upload the dataset so we can troubleshoot whats going on.

![image](https://user-images.githubusercontent.com/58118658/103179546-41e9d780-485b-11eb-8bec-e91185469229.png)

**Comment by minhaajre** [comment]
it should have been open https://colab.research.google.com/drive/1BPfpFh47FuWTE2gXaN63gsJpM-6I0HgH?usp=sharing

**Comment by minhaajre** [comment]
![image](https://user-images.githubusercontent.com/59568642/103179658-04fc0000-48b0-11eb-9b2b-099090cefd81.png)

**Comment by Yard1** [comment]
I don't think the dataset files are included.

**Comment by minhaajre** [comment]
It should be. Its here anyways https://www.kaggle.com/c/house-prices-advanced-regression-techniques

**Comment by Yard1** [comment]
The issue is the `feature_interaction=True` parameter in `setup()`. It will create interactions for all columns, which, considering how many there are, will quickly cause a memory issue. `feature_interaction=True` should only be used on datasets with a small amount of columns.

**Comment by minhaajre** [comment]
Its probably the smallest dataset i know of. It should be able to compute that without issues. :(

**Comment by Yard1** [comment]
The issue is with `feature_interaction=True` `setup()` parameter. It will try to create feature interactions between all columns - and while this dataset has a small number of rows, it has a large number of columns, causing it to quickly run out of memory. `feature_interaction` should only be used on dataset with a small number of columns. After removing that option, the notebook works fine.

**Comment by rajpratyush** [comment]
yes, Because Creating a new feature through interaction of existing features is known as feature interaction and in PyCaret it is achieved using feature_interaction and feature_ratio parameters within setup. Feature interaction creates new features by multiplying two variables (a * b), while feature ratios create new features but by calculating the ratios of existing features (a / b). and as your dataset already has a large number of columns using feature_interaction will add new features to the dataset making it difficult to process leading to crashing of session.

one solution could be after using the feature_interaction drop the unnescessary columns so as to reduce the number of columns in the dataset.
