### ISSUE TITLE
[HELP] How to list discarded features when using feature_selection?

### ISSUE THREAD

**Issue by almirb** [pycaret/pycaret#984]
Hello! 
I'm new to PyCaret and read the documentation about feature_selection...  but I didn't find a way to get all features discarded with the selected threshold.
How can I do this?

Thanks and congratulations for this beautiful piece of software! :)

**Comment by Yard1** [comment]
This is not yet supported natively, but you can get a list of columns that were kept with `get_config('prep_pipe').named_steps["feature_select"].selected_columns_test` after running `setup()`. You can then compare it with the starting columns.

**Comment by pycaret** [comment]
@almirb Or you can also access the column names from the training set by using `get_config('X_train').columns`. You can compare this list with the original dataset to determine which columns were ignored from the original dataset. However, note that `feature_selection` is not the only parameter because of which features are dropped/ignored. There are other parameters that can have the effect on certain columns being removed, such as `remove_multicollinearity`, `remove_perfect_collinearity`, any columns explicitly passed to be ignored in `ignore_features` parameter, Any column inferred as `ID`, or `Datetime` is also dropped from the training set.

**Comment by almirb** [comment]
Very nice! Both solutions (@Yard1  and @pycaret ) worked well to list the remaining columns after ```features_selection``` process. Thanks!

But I have some category columns.  A thing that I couldn't do, It's to get the columns _after_ the ```one_hot_encoding``` (where a lot of columns are created) and _before_ ```features_selection``` (where some columns are removed).
I think I'll end doing the ```one_hot_encoding``` manually using scikit_learn before running ```setup```.

Do you know another way of getting that info?

**Comment by sahil0094** [comment]
set(orig_dataframe.columns)-set(get_config('X_train').columns)

**Comment by almirb** [comment]
It worked!! Thanks @sahil0094 !
